### ISSUE TITLE
Fix tests on macOS M1.

### ISSUE THREAD

**Issue by maxim-ponomarev** [OpenHFT/Posix#16]
Upgrade `jnr-ffi` to allow running on newer macOS versions (which require for signed binaries).
Disable tests for macOS for unsupported system calls.

**Comment by hft-team-city** [comment]
Released in [Posix-2.23ea0](https://github.com/OpenHFT/Posix/releases/posix-2.23ea0), [BOM-2.23ea92](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea92)

**Comment by hft-team-city** [comment]
Released in [Posix-2.22.10](https://github.com/OpenHFT/Posix/releases/posix-2.22.10), [BOM-2.22.165](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.165)
